#!/bin/sh
#
### BEGIN INIT INFO
# Provides:             download_files
# Required-Start:    $network $syslog $named $local_fs $remote_fs
# Required-Stop:     $network $syslog $named $local_fs $remote_fs
# Should-Start:      dahdi misdn lcr wanrouter mysql postgresql
# Should-Stop:       dahdi misdn lcr wanrouter mysql postgresql
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    download_files script
# Description:          download_files script
### END INIT INFO
# Script Para la Gestion de Descarga de Archivos 
# Creado por la unidad de Infraestructura de Tecnologia de Informacion
#
# Actualizaciones:
# 
#
# Credits: 
# Created by Jonathan Melendez el 26/01/2016
# Comienzo del Servicio
PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

#Arguments

project="$2"

start(){
	echo "Starting service: download_files_nap.php"
	amirunnign=`ps -ef |grep /var/www/$project/script/download_files_nap.php|grep -v grep|wc -l`
	case $amirunnign in
	0)
		cd /var/www/$project/script/
		php -f /var/www/$project/script/download_files_nap.php $project > /var/www/$project/script/download_nap.log &
		amirunnign=`ps -ef |grep /var/www/$project/script/download_files_nap.php|grep -v grep|wc -l`
		case $amirunnign in
		0)
			echo ""
			echo "ALERT: Failed to start Service"
			echo ""
			;;
		*)
			mypid=`ps -ef | grep /var/www/$project/script/download_files_nap.php | grep -v grep | awk '{print $2}'`
			echo "Service Started Successfully at PID: $mypid"
			echo ""
			;;
		esac
		;;
	*)
		mypid=`ps -ef | grep /var/www/$project/script/download_files_nap.php | grep -v grep | awk '{print $2}'`
		echo ""
		echo "Service Already running at PID: $mypid"
		echo ""
		;;
	esac
}

stop(){
	amirunnign=`ps -ef |grep /var/www/$project/script/download_files_nap.php|grep -v grep|wc -l`
	case $amirunnign in
	0)
		echo ""
		echo "ALERT: Service Not Found. Nothing to stop"
		echo ""
		;;
	*)
		mypid=`ps -ef | grep /var/www/$project/script/download_files_nap.php | grep -v grep | awk '{print $2}'`
		echo ""
		echo "Stopping service: /var/www/$project/script/download_files_nap.php at PID: $mypid"
		ps -ef | grep /var/www/$project/script/download_files_nap.php | grep -v grep | awk '{print $2}' | xargs kill -9 > /dev/null 2>&1
		echo ""
		amirunnign=`ps -ef |grep /var/www/$project/script/download_files_nap.php|grep -v grep|wc -l`
		case $amirunnign in
		0)
			echo ""
			echo "Service Successfully Stopped"
			echo ""
			;;
		*)
			mypid=`ps -ef | grep /var/www/$project/script/download_files_nap.php| grep -v grep | awk '{print $2}'`
			echo ""
			echo "ALERT: Failed to stop service. Service still running at PID: $mypid"
			echo ""
			;;
		esac
		;;
	esac
}

status(){
	amirunnign=`ps -ef |grep /var/www/$project/script/download_files_nap.php|grep -v grep|wc -l`
	mypid=`ps -ef | grep /var/www/$project/script/download_files_nap.php | grep -v grep | awk '{print $2}'`
	echo ""
	case $amirunnign in
	0)
		echo "Service NOT Running"
		;;
	*)
		echo "Service RUNNING at PID: $mypid"
		;;
	esac
	echo ""
}


case "$1" in
start)
	start
	;;
stop)
	stop
	;;
restart)
	stop
	start
	;;
status)
	status
	;;
*)
	echo $"Usar: $0 {start|stop|restart|status}"
	exit 1
esac

exit 0
