#!/bin/sh
#
### BEGIN INIT INFO
# Provides:             file_distributor
# Required-Start:    $network $syslog $named $local_fs $remote_fs
# Required-Stop:     $network $syslog $named $local_fs $remote_fs
# Should-Start:      dahdi misdn lcr wanrouter mysql postgresql
# Should-Stop:       dahdi misdn lcr wanrouter mysql postgresql
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    file_distributor siccanp
# Description:          file_distributor siccanp
### END INIT INFO
# Script Para la Gestion de Descarga de Archivos 
# Creado por la unidad de Infraestructura Tecnologica
#
# Actualizaciones:
#	07/07/2016= Se Añade capa para determinar logs desde el instalador, adicionalmente se transforma en servicio file_distributor
#	02/03/2016= Añadiendo Compatibilidad multi-servicios en el path $2 para start, stop y restart 
#
# Credits: 
# Created by Jonathan Melendez el 26/01/2016
# Comienzo del Servicio
PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin

#Arguments
projectlist='
	siccanp'

	if [ ! -z $2 ]
	then
		case $2 in
		siccanp)
			projectlist="siccanp"
		;;
		*)
			echo "Usage: $0 start|stop|restart|status followed of project siccanp"
			exit 0
		;;
		esac
	fi

start(){

	for svc in $projectlist
	do
	echo "Starting service: download files in $svc"
	echo ""
	amirunnign=`ps -ef |grep /var/www/$svc/script/file_distributor.php |grep -v grep|wc -l`
	case $amirunnign in
	0)
		if [ -f "/var/www/$svc/script/file_distributor.php" ] 
		then
		php -f /var/www/$svc/script/file_distributor.php $svc > CANTVRUTA/logs/marcadores/file_distributor-$svc.log &
		amirunnign=`ps -ef |grep /var/www/$svc/script/file_distributor.php|grep -v grep|wc -l`
		case $amirunnign in
		0)
			echo "ALERT: Failed to start Service in $svc"
			echo ""
			;;
		*)
			mypid=`ps -ef | grep /var/www/$svc/script/file_distributor.php | grep -v grep | awk '{print $2}'`
			echo "Service Started Successfully at PID: $mypid in $svc"
			echo ""
			;;
		esac
		else
		echo "The folder of project $svc in /var/www/ NOT EXIST, obviating folder"
		echo ""
		fi
		;;
	*)
		mypid=`ps -ef | grep /var/www/$svc/script/file_distributor.php | grep -v grep | awk '{print $2}'`
		echo "Service Already running at PID: $mypid"
		echo ""
		;;
	esac
	done
	}

stop(){

        for svc in $projectlist
        do
	amirunnign=`ps -ef |grep /var/www/$svc/script/file_distributor.php|grep -v grep|wc -l`
	case $amirunnign in
	0)
		echo "ALERT: Service download files in $svc NOT RUNNING. Nothing to stop"
		echo ""
		;;
	*)
		mypid=`ps -ef | grep /var/www/$svc/script/file_distributor.php | grep -v grep | awk '{print $2}'`
		echo "Stopping service: download files in $svc at PID: $mypid"
		ps -ef | grep /var/www/$svc/script/file_distributor.php | grep -v grep | awk '{print $2}' | xargs kill -9 > /dev/null 2>&1
		echo ""
		amirunnign=`ps -ef |grep /var/www/$svc/script/file_distributor.php|grep -v grep|wc -l`
		case $amirunnign in
		0)
			echo "Service download files in $svc Successfully Stopped"
			echo ""
			;;
		*)
			mypid=`ps -ef | grep /var/www/$svc/script/file_distributor.php | grep -v grep | awk '{print $2}'`
			echo "ALERT: Failed to stop service download files in $svc. Service still running at PID: $mypid"
			echo ""
			;;
		esac
		;;
	esac
	done
	}

status(){

        for svc in $projectlist
        do
	amirunnign=`ps -ef |grep /var/www/$svc/script/file_distributor.php|grep -v grep|wc -l`
	mypid=`ps -ef | grep /var/www/$svc/script/file_distributor.php | grep -v grep | awk '{print $2}'`
	echo ""
	case $amirunnign in
	0)
		echo "Service download files in $svc NOT Running"
		;;
	*)
		echo "Service download files in $svc RUNNING at PID: $mypid"
		;;
	esac
	echo ""
	done
	}	


case "$1" in
start)
	start
	;;
stop)
	echo "¡¡¡¡STOPPING SERVICES!!!!"
	stop
	;;
restart)
	echo "¡¡¡¡STOPPING SERVICES!!!!"
	stop
	echo "Wait 5 seconds...."
	sleep 5
	echo "¡¡¡STARTING SERVICES!!!!"
	start
	;;
status)
	echo "¡¡¡¡STATUS OF SERVICES!!!!"
	status
	;;
*)
	echo "Usar: $0 {start|stop|restart|status} seguido del servicio siccanp"
	exit 1
esac

exit 0
